import {
  Utensils,
  UtensilsCrossed,
  Pizza,
  Sandwich,
  Salad,
  Soup,
  Fish,
  Drumstick,
  Egg,
  Beef,
  Ham,
  Coffee,
  Wine,
  Beer,
  Martini,
  CupSoda,
  Cake,
  Cookie,
  Croissant,
  Donut,
  Candy,
  IceCreamCone,
  Apple,
  Banana,
  Cherry,
  Grape,
  Citrus,
  Carrot,
  Milk,
  Nut,
  Wheat,
  Vegan,
  ShoppingCart,
  ShoppingBag,
  ShoppingBasket,
  Store,
  Tag,
  Barcode,
  Percent,
  BadgePercent,
  Gift,
  Shirt,
  Glasses,
  Watch,
  Gem,
  Diamond,
  Crown,
  Footprints,
  Package,
  Boxes,
  Scissors,
  SprayCan,
  Car,
  BusFront,
  TrainFront,
  TramFront,
  Plane,
  PlaneTakeoff,
  Rocket,
  Bike,
  Truck,
  Tractor,
  Forklift,
  Caravan,
  Ship,
  Sailboat,
  Anchor,
  Fuel,
  CarTaxiFront,
  CircleParking,
  Navigation,
  Milestone,
  House,
  Warehouse,
  Bed,
  Sofa,
  Armchair,
  Lamp,
  Bath,
  ShowerHead,
  CookingPot,
  WashingMachine,
  Refrigerator,
  DoorOpen,
  Key,
  Plug,
  Wrench,
  Lightbulb,
  Hammer,
  Paintbrush,
  PaintRoller,
  Brush,
  Blinds,
  Fence,
  Trash2,
  Recycle,
  Wifi,
  Router,
  Signal,
  Antenna,
  SatelliteDish,
  Smartphone,
  Phone,
  Droplet,
  Flame,
  Zap,
  Mail,
  AtSign,
  Send,
  Inbox,
  FileText,
  Receipt,
  Newspaper,
  Calendar,
  Bell,
  HeartPulse,
  Stethoscope,
  Ambulance,
  Hospital,
  Pill,
  Tablets,
  Syringe,
  Cross,
  Activity,
  Brain,
  Bandage,
  Thermometer,
  Microscope,
  TestTube,
  Dumbbell,
  Weight,
  Accessibility,
  Ear,
  Eye,
  Smile,
  GraduationCap,
  Book,
  BookOpen,
  BookMarked,
  Notebook,
  Pencil,
  Pen,
  Highlighter,
  PencilRuler,
  Library,
  Backpack,
  Ruler,
  Calculator,
  Atom,
  Languages,
  Award,
  School,
  Briefcase,
  BriefcaseBusiness,
  Laptop,
  Monitor,
  Printer,
  Building,
  Building2,
  Factory,
  Presentation,
  HardHat,
  Handshake,
  Clock,
  Timer,
  Target,
  Goal,
  NotebookPen,
  ClipboardList,
  Mailbox,
  ChartColumn,
  ChartLine,
  ChartPie,
  Film,
  Clapperboard,
  Music,
  Headphones,
  Guitar,
  Piano,
  Drum,
  Radio,
  Disc,
  Disc3,
  Mic,
  MicVocal,
  Gamepad2,
  Joystick,
  Tv,
  Ticket,
  Palette,
  Camera,
  Popcorn,
  Drama,
  PartyPopper,
  Dices,
  Puzzle,
  Spade,
  Club,
  Volleyball,
  Trophy,
  Medal,
  MapPin,
  Map,
  Compass,
  Globe,
  Luggage,
  Hotel,
  Tent,
  Mountain,
  MountainSnow,
  TreePalm,
  Trees,
  TreeDeciduous,
  TreePine,
  Flower,
  Flower2,
  Umbrella,
  Sun,
  Cloud,
  CloudSun,
  CloudRain,
  Wind,
  Snowflake,
  Waves,
  Shell,
  Leaf,
  Sprout,
  Dog,
  Cat,
  Bird,
  Rabbit,
  Turtle,
  Rat,
  Squirrel,
  Snail,
  Worm,
  Bug,
  Feather,
  Bone,
  PawPrint,
  Baby,
  User,
  UserRound,
  Users,
  Contact,
  PersonStanding,
  UserPlus,
  Heart,
  HandHeart,
  HeartHandshake,
  Banknote,
  Wallet,
  WalletCards,
  PiggyBank,
  CreditCard,
  Landmark,
  Coins,
  DollarSign,
  CircleDollarSign,
  BadgeDollarSign,
  Euro,
  PoundSterling,
  JapaneseYen,
  IndianRupee,
  Bitcoin,
  HandCoins,
  Scale,
  TrendingUp,
  TrendingDown,
  Star,
  Sparkles,
  Bookmark,
  Flag,
  Hash,
  Shapes,
  Grid3x3,
  Box,
  Circle,
  MoreHorizontal,
  type LucideIcon,
} from 'lucide-react';
import type { IconKey } from '@finance/contracts';

/** kebab-case icon key -> lucide component. Keys must match ICON_KEYS in contracts. */
export const ICON_MAP: Record<IconKey, LucideIcon> = {
  // Alimentação
  utensils: Utensils,
  'utensils-crossed': UtensilsCrossed,
  pizza: Pizza,
  sandwich: Sandwich,
  salad: Salad,
  soup: Soup,
  fish: Fish,
  drumstick: Drumstick,
  egg: Egg,
  beef: Beef,
  ham: Ham,
  coffee: Coffee,
  wine: Wine,
  beer: Beer,
  martini: Martini,
  'cup-soda': CupSoda,
  cake: Cake,
  cookie: Cookie,
  croissant: Croissant,
  donut: Donut,
  candy: Candy,
  'ice-cream-cone': IceCreamCone,
  apple: Apple,
  banana: Banana,
  cherry: Cherry,
  grape: Grape,
  citrus: Citrus,
  carrot: Carrot,
  milk: Milk,
  nut: Nut,
  wheat: Wheat,
  vegan: Vegan,
  // Compras
  'shopping-cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  'shopping-basket': ShoppingBasket,
  store: Store,
  tag: Tag,
  barcode: Barcode,
  percent: Percent,
  'badge-percent': BadgePercent,
  gift: Gift,
  shirt: Shirt,
  glasses: Glasses,
  watch: Watch,
  gem: Gem,
  diamond: Diamond,
  crown: Crown,
  footprints: Footprints,
  package: Package,
  boxes: Boxes,
  scissors: Scissors,
  'spray-can': SprayCan,
  // Transporte
  car: Car,
  'bus-front': BusFront,
  'train-front': TrainFront,
  'tram-front': TramFront,
  plane: Plane,
  'plane-takeoff': PlaneTakeoff,
  rocket: Rocket,
  bike: Bike,
  truck: Truck,
  tractor: Tractor,
  forklift: Forklift,
  caravan: Caravan,
  ship: Ship,
  sailboat: Sailboat,
  anchor: Anchor,
  fuel: Fuel,
  'car-taxi-front': CarTaxiFront,
  'circle-parking': CircleParking,
  navigation: Navigation,
  milestone: Milestone,
  // Casa
  house: House,
  warehouse: Warehouse,
  bed: Bed,
  sofa: Sofa,
  armchair: Armchair,
  lamp: Lamp,
  bath: Bath,
  'shower-head': ShowerHead,
  'cooking-pot': CookingPot,
  'washing-machine': WashingMachine,
  refrigerator: Refrigerator,
  'door-open': DoorOpen,
  key: Key,
  plug: Plug,
  wrench: Wrench,
  lightbulb: Lightbulb,
  hammer: Hammer,
  paintbrush: Paintbrush,
  'paint-roller': PaintRoller,
  brush: Brush,
  blinds: Blinds,
  fence: Fence,
  'trash-2': Trash2,
  recycle: Recycle,
  // Contas & Serviços
  wifi: Wifi,
  router: Router,
  signal: Signal,
  antenna: Antenna,
  'satellite-dish': SatelliteDish,
  smartphone: Smartphone,
  phone: Phone,
  droplet: Droplet,
  flame: Flame,
  zap: Zap,
  mail: Mail,
  'at-sign': AtSign,
  send: Send,
  inbox: Inbox,
  'file-text': FileText,
  receipt: Receipt,
  newspaper: Newspaper,
  calendar: Calendar,
  bell: Bell,
  // Saúde
  'heart-pulse': HeartPulse,
  stethoscope: Stethoscope,
  ambulance: Ambulance,
  hospital: Hospital,
  pill: Pill,
  tablets: Tablets,
  syringe: Syringe,
  cross: Cross,
  activity: Activity,
  brain: Brain,
  bandage: Bandage,
  thermometer: Thermometer,
  microscope: Microscope,
  'test-tube': TestTube,
  dumbbell: Dumbbell,
  weight: Weight,
  accessibility: Accessibility,
  ear: Ear,
  eye: Eye,
  smile: Smile,
  // Educação
  'graduation-cap': GraduationCap,
  book: Book,
  'book-open': BookOpen,
  'book-marked': BookMarked,
  notebook: Notebook,
  pencil: Pencil,
  pen: Pen,
  highlighter: Highlighter,
  'pencil-ruler': PencilRuler,
  library: Library,
  backpack: Backpack,
  ruler: Ruler,
  calculator: Calculator,
  atom: Atom,
  languages: Languages,
  award: Award,
  school: School,
  // Trabalho
  briefcase: Briefcase,
  'briefcase-business': BriefcaseBusiness,
  laptop: Laptop,
  monitor: Monitor,
  printer: Printer,
  building: Building,
  'building-2': Building2,
  factory: Factory,
  presentation: Presentation,
  'hard-hat': HardHat,
  handshake: Handshake,
  clock: Clock,
  timer: Timer,
  target: Target,
  goal: Goal,
  'notebook-pen': NotebookPen,
  'clipboard-list': ClipboardList,
  mailbox: Mailbox,
  'chart-column': ChartColumn,
  'chart-line': ChartLine,
  'chart-pie': ChartPie,
  // Lazer & Entretenimento
  film: Film,
  clapperboard: Clapperboard,
  music: Music,
  headphones: Headphones,
  guitar: Guitar,
  piano: Piano,
  drum: Drum,
  radio: Radio,
  disc: Disc,
  'disc-3': Disc3,
  mic: Mic,
  'mic-vocal': MicVocal,
  'gamepad-2': Gamepad2,
  joystick: Joystick,
  tv: Tv,
  ticket: Ticket,
  palette: Palette,
  camera: Camera,
  popcorn: Popcorn,
  drama: Drama,
  'party-popper': PartyPopper,
  dices: Dices,
  puzzle: Puzzle,
  spade: Spade,
  club: Club,
  volleyball: Volleyball,
  trophy: Trophy,
  medal: Medal,
  // Viagem & Natureza
  'map-pin': MapPin,
  map: Map,
  compass: Compass,
  globe: Globe,
  luggage: Luggage,
  hotel: Hotel,
  tent: Tent,
  mountain: Mountain,
  'mountain-snow': MountainSnow,
  'tree-palm': TreePalm,
  trees: Trees,
  'tree-deciduous': TreeDeciduous,
  'tree-pine': TreePine,
  flower: Flower,
  'flower-2': Flower2,
  umbrella: Umbrella,
  sun: Sun,
  cloud: Cloud,
  'cloud-sun': CloudSun,
  'cloud-rain': CloudRain,
  wind: Wind,
  snowflake: Snowflake,
  waves: Waves,
  shell: Shell,
  leaf: Leaf,
  sprout: Sprout,
  // Pets
  dog: Dog,
  cat: Cat,
  bird: Bird,
  rabbit: Rabbit,
  turtle: Turtle,
  rat: Rat,
  squirrel: Squirrel,
  snail: Snail,
  worm: Worm,
  bug: Bug,
  feather: Feather,
  bone: Bone,
  'paw-print': PawPrint,
  // Família & Pessoas
  baby: Baby,
  user: User,
  'user-round': UserRound,
  users: Users,
  contact: Contact,
  'person-standing': PersonStanding,
  'user-plus': UserPlus,
  heart: Heart,
  'hand-heart': HandHeart,
  'heart-handshake': HeartHandshake,
  // Finanças
  banknote: Banknote,
  wallet: Wallet,
  'wallet-cards': WalletCards,
  'piggy-bank': PiggyBank,
  'credit-card': CreditCard,
  landmark: Landmark,
  coins: Coins,
  'dollar-sign': DollarSign,
  'circle-dollar-sign': CircleDollarSign,
  'badge-dollar-sign': BadgeDollarSign,
  euro: Euro,
  'pound-sterling': PoundSterling,
  'japanese-yen': JapaneseYen,
  'indian-rupee': IndianRupee,
  bitcoin: Bitcoin,
  'hand-coins': HandCoins,
  scale: Scale,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  // Outros
  star: Star,
  sparkles: Sparkles,
  bookmark: Bookmark,
  flag: Flag,
  hash: Hash,
  shapes: Shapes,
  'grid-3x3': Grid3x3,
  box: Box,
  circle: Circle,
  'more-horizontal': MoreHorizontal,
};

export function getIcon(key: IconKey): LucideIcon {
  return ICON_MAP[key] ?? Tag;
}
