import {
  Utensils,
  ShoppingCart,
  ShoppingBag,
  House,
  Car,
  Plane,
  Bus,
  TrainFront,
  Fuel,
  HeartPulse,
  Stethoscope,
  Pill,
  Dumbbell,
  GraduationCap,
  Book,
  Briefcase,
  Laptop,
  Wifi,
  Smartphone,
  Gift,
  Shirt,
  Baby,
  Dog,
  Cat,
  Coffee,
  Wine,
  Beer,
  Pizza,
  Banknote,
  Wallet,
  PiggyBank,
  CreditCard,
  Landmark,
  TrendingUp,
  TrendingDown,
  Receipt,
  HandCoins,
  Film,
  Music,
  Gamepad2,
  Tv,
  Ticket,
  Palette,
  Camera,
  Bed,
  MapPin,
  Wrench,
  Lightbulb,
  Droplet,
  Flame,
  Leaf,
  Sun,
  Umbrella,
  Sparkles,
  Star,
  Tag,
  Package,
  Truck,
  Bike,
  Heart,
  type LucideIcon,
} from 'lucide-react';
import type { IconKey } from '@finance/contracts';

/** kebab-case icon key -> lucide component. Keys must match ICON_KEYS in contracts. */
export const ICON_MAP: Record<IconKey, LucideIcon> = {
  utensils: Utensils,
  'shopping-cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  house: House,
  car: Car,
  plane: Plane,
  bus: Bus,
  'train-front': TrainFront,
  fuel: Fuel,
  'heart-pulse': HeartPulse,
  stethoscope: Stethoscope,
  pill: Pill,
  dumbbell: Dumbbell,
  'graduation-cap': GraduationCap,
  book: Book,
  briefcase: Briefcase,
  laptop: Laptop,
  wifi: Wifi,
  smartphone: Smartphone,
  gift: Gift,
  shirt: Shirt,
  baby: Baby,
  dog: Dog,
  cat: Cat,
  coffee: Coffee,
  wine: Wine,
  beer: Beer,
  pizza: Pizza,
  banknote: Banknote,
  wallet: Wallet,
  'piggy-bank': PiggyBank,
  'credit-card': CreditCard,
  landmark: Landmark,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  receipt: Receipt,
  'hand-coins': HandCoins,
  film: Film,
  music: Music,
  'gamepad-2': Gamepad2,
  tv: Tv,
  ticket: Ticket,
  palette: Palette,
  camera: Camera,
  bed: Bed,
  'map-pin': MapPin,
  wrench: Wrench,
  lightbulb: Lightbulb,
  droplet: Droplet,
  flame: Flame,
  leaf: Leaf,
  sun: Sun,
  umbrella: Umbrella,
  sparkles: Sparkles,
  star: Star,
  tag: Tag,
  package: Package,
  truck: Truck,
  bike: Bike,
  heart: Heart,
};

export function getIcon(key: IconKey): LucideIcon {
  return ICON_MAP[key] ?? Tag;
}
