import { z } from 'zod';

/**
 * Icon keys are kebab-case lucide-react icon names. The UI IconPicker maps each
 * key to its lucide component (ICON_MAP) and lays them out by category (ICON_GROUPS).
 * Keep keys in sync with the picker's icon map.
 */
export const ICON_KEYS = [
  // Alimentação
  'utensils',
  'utensils-crossed',
  'pizza',
  'sandwich',
  'salad',
  'soup',
  'fish',
  'drumstick',
  'egg',
  'beef',
  'ham',
  'coffee',
  'wine',
  'beer',
  'martini',
  'cup-soda',
  'cake',
  'cookie',
  'croissant',
  'donut',
  'candy',
  'ice-cream-cone',
  'apple',
  'banana',
  'cherry',
  'grape',
  'citrus',
  'carrot',
  'milk',
  'nut',
  'wheat',
  'vegan',
  // Compras
  'shopping-cart',
  'shopping-bag',
  'shopping-basket',
  'store',
  'tag',
  'barcode',
  'percent',
  'badge-percent',
  'gift',
  'shirt',
  'glasses',
  'watch',
  'gem',
  'diamond',
  'crown',
  'footprints',
  'package',
  'boxes',
  'scissors',
  'spray-can',
  // Transporte
  'car',
  'bus-front',
  'train-front',
  'tram-front',
  'plane',
  'plane-takeoff',
  'rocket',
  'bike',
  'truck',
  'tractor',
  'forklift',
  'caravan',
  'ship',
  'sailboat',
  'anchor',
  'fuel',
  'car-taxi-front',
  'circle-parking',
  'navigation',
  'milestone',
  // Casa
  'house',
  'warehouse',
  'bed',
  'sofa',
  'armchair',
  'lamp',
  'bath',
  'shower-head',
  'cooking-pot',
  'washing-machine',
  'refrigerator',
  'door-open',
  'key',
  'plug',
  'wrench',
  'lightbulb',
  'hammer',
  'paintbrush',
  'paint-roller',
  'brush',
  'blinds',
  'fence',
  'trash-2',
  'recycle',
  // Contas & Serviços
  'wifi',
  'router',
  'signal',
  'antenna',
  'satellite-dish',
  'smartphone',
  'phone',
  'droplet',
  'flame',
  'zap',
  'mail',
  'at-sign',
  'send',
  'inbox',
  'file-text',
  'receipt',
  'newspaper',
  'calendar',
  'bell',
  // Saúde
  'heart-pulse',
  'stethoscope',
  'ambulance',
  'hospital',
  'pill',
  'tablets',
  'syringe',
  'cross',
  'activity',
  'brain',
  'bandage',
  'thermometer',
  'microscope',
  'test-tube',
  'dumbbell',
  'weight',
  'accessibility',
  'ear',
  'eye',
  'smile',
  // Educação
  'graduation-cap',
  'book',
  'book-open',
  'book-marked',
  'notebook',
  'pencil',
  'pen',
  'highlighter',
  'pencil-ruler',
  'library',
  'backpack',
  'ruler',
  'calculator',
  'atom',
  'languages',
  'award',
  'school',
  // Trabalho
  'briefcase',
  'briefcase-business',
  'laptop',
  'monitor',
  'printer',
  'building',
  'building-2',
  'factory',
  'presentation',
  'hard-hat',
  'handshake',
  'clock',
  'timer',
  'target',
  'goal',
  'notebook-pen',
  'clipboard-list',
  'mailbox',
  'chart-column',
  'chart-line',
  'chart-pie',
  // Lazer & Entretenimento
  'film',
  'clapperboard',
  'music',
  'headphones',
  'guitar',
  'piano',
  'drum',
  'radio',
  'disc',
  'disc-3',
  'mic',
  'mic-vocal',
  'gamepad-2',
  'joystick',
  'tv',
  'ticket',
  'palette',
  'camera',
  'popcorn',
  'drama',
  'party-popper',
  'dices',
  'puzzle',
  'spade',
  'club',
  'volleyball',
  'trophy',
  'medal',
  // Viagem & Natureza
  'map-pin',
  'map',
  'compass',
  'globe',
  'luggage',
  'hotel',
  'tent',
  'mountain',
  'mountain-snow',
  'tree-palm',
  'trees',
  'tree-deciduous',
  'tree-pine',
  'flower',
  'flower-2',
  'umbrella',
  'sun',
  'cloud',
  'cloud-sun',
  'cloud-rain',
  'wind',
  'snowflake',
  'waves',
  'shell',
  'leaf',
  'sprout',
  // Pets
  'dog',
  'cat',
  'bird',
  'rabbit',
  'turtle',
  'rat',
  'squirrel',
  'snail',
  'worm',
  'bug',
  'feather',
  'bone',
  'paw-print',
  // Família & Pessoas
  'baby',
  'user',
  'user-round',
  'users',
  'contact',
  'person-standing',
  'user-plus',
  'heart',
  'hand-heart',
  'heart-handshake',
  // Finanças
  'banknote',
  'wallet',
  'wallet-cards',
  'piggy-bank',
  'credit-card',
  'landmark',
  'coins',
  'dollar-sign',
  'circle-dollar-sign',
  'badge-dollar-sign',
  'euro',
  'pound-sterling',
  'japanese-yen',
  'indian-rupee',
  'bitcoin',
  'hand-coins',
  'scale',
  'trending-up',
  'trending-down',
  // Outros
  'star',
  'sparkles',
  'bookmark',
  'flag',
  'hash',
  'shapes',
  'grid-3x3',
  'box',
  'circle',
  'more-horizontal',
] as const;

export const iconKeySchema = z.enum(ICON_KEYS);

export type IconKey = z.infer<typeof iconKeySchema>;

/** Portuguese search labels (used by the picker's search). Falls back to the humanized key. */
export const ICON_LABELS: Partial<Record<IconKey, string>> = {
  utensils: 'restaurante talheres comida',
  'utensils-crossed': 'restaurante talheres',
  pizza: 'pizza',
  sandwich: 'lanche sanduíche',
  salad: 'salada saudável',
  soup: 'sopa caldo',
  fish: 'peixe',
  drumstick: 'frango carne',
  egg: 'ovo',
  beef: 'carne bife',
  ham: 'presunto frios',
  coffee: 'café',
  wine: 'vinho bebida',
  beer: 'cerveja bebida bar',
  martini: 'drink coquetel bar',
  'cup-soda': 'refrigerante bebida',
  cake: 'bolo doce festa',
  cookie: 'biscoito bolacha',
  croissant: 'pão padaria',
  donut: 'rosquinha doce',
  candy: 'doce bala',
  'ice-cream-cone': 'sorvete',
  apple: 'fruta maçã',
  banana: 'banana fruta',
  cherry: 'cereja fruta',
  grape: 'uva fruta',
  citrus: 'laranja limão cítrico fruta',
  carrot: 'legume verdura cenoura',
  milk: 'leite laticínio',
  nut: 'noz castanha',
  wheat: 'trigo grão cereal',
  vegan: 'vegano vegetariano',
  'shopping-cart': 'compras carrinho mercado',
  'shopping-bag': 'compras sacola',
  'shopping-basket': 'compras cesta',
  store: 'loja mercado',
  tag: 'etiqueta preço',
  barcode: 'código de barras',
  percent: 'desconto porcentagem',
  'badge-percent': 'promoção desconto oferta',
  gift: 'presente',
  shirt: 'roupa camiseta vestuário',
  glasses: 'óculos',
  watch: 'relógio',
  gem: 'joia diamante',
  diamond: 'diamante joia luxo',
  crown: 'coroa luxo premium',
  footprints: 'sapato calçado',
  package: 'pacote encomenda',
  boxes: 'caixas estoque',
  scissors: 'cabeleireiro salão tesoura',
  'spray-can': 'beleza cosmético',
  car: 'carro automóvel',
  'bus-front': 'ônibus transporte',
  'train-front': 'trem metrô',
  'tram-front': 'bonde vlt',
  plane: 'avião voo',
  'plane-takeoff': 'avião viagem',
  rocket: 'foguete',
  bike: 'bicicleta',
  truck: 'caminhão frete',
  tractor: 'trator',
  forklift: 'empilhadeira',
  caravan: 'trailer caravana',
  ship: 'navio barco',
  sailboat: 'barco vela',
  anchor: 'âncora porto',
  fuel: 'combustível gasolina posto',
  'car-taxi-front': 'táxi uber corrida',
  'circle-parking': 'estacionamento',
  navigation: 'navegação gps rota',
  milestone: 'marco estrada pedágio',
  house: 'casa moradia aluguel',
  warehouse: 'galpão depósito',
  bed: 'cama quarto',
  sofa: 'sofá móvel',
  armchair: 'poltrona móvel',
  lamp: 'luminária abajur',
  bath: 'banheira banheiro',
  'shower-head': 'chuveiro banho',
  'cooking-pot': 'panela cozinha',
  'washing-machine': 'lavadora máquina lavar',
  refrigerator: 'geladeira',
  'door-open': 'porta',
  key: 'chave',
  plug: 'tomada energia',
  wrench: 'ferramenta manutenção conserto',
  lightbulb: 'lâmpada luz',
  hammer: 'martelo reforma',
  paintbrush: 'pincel pintura',
  'paint-roller': 'rolo pintura parede',
  brush: 'pincel escova',
  blinds: 'persiana cortina',
  fence: 'cerca quintal',
  'trash-2': 'lixo lixeira',
  recycle: 'reciclagem',
  wifi: 'internet wifi',
  router: 'roteador internet',
  signal: 'sinal rede',
  antenna: 'antena',
  'satellite-dish': 'antena parabólica tv',
  smartphone: 'celular telefone',
  phone: 'telefone ligação',
  droplet: 'água',
  flame: 'gás fogo',
  zap: 'energia luz eletricidade',
  mail: 'email correspondência',
  'at-sign': 'arroba email',
  send: 'enviar transferência',
  inbox: 'caixa de entrada',
  'file-text': 'documento conta boleto',
  receipt: 'recibo nota fiscal',
  newspaper: 'jornal assinatura notícia',
  calendar: 'calendário agenda',
  bell: 'notificação lembrete',
  'heart-pulse': 'saúde batimento',
  stethoscope: 'médico consulta',
  ambulance: 'ambulância emergência',
  hospital: 'hospital',
  pill: 'remédio farmácia',
  tablets: 'comprimido remédio',
  syringe: 'vacina injeção',
  cross: 'hospital saúde',
  activity: 'atividade saúde',
  brain: 'terapia mente psicólogo',
  bandage: 'curativo machucado',
  thermometer: 'febre temperatura',
  microscope: 'laboratório exame',
  'test-tube': 'exame laboratório',
  dumbbell: 'academia exercício musculação',
  weight: 'peso balança academia',
  accessibility: 'acessibilidade',
  ear: 'ouvido audição',
  eye: 'olho visão oftalmo',
  smile: 'dentista sorriso',
  'graduation-cap': 'formatura faculdade educação',
  book: 'livro leitura',
  'book-open': 'livro estudo',
  'book-marked': 'livro marcador',
  notebook: 'caderno anotação',
  pencil: 'lápis escrever',
  pen: 'caneta escrever',
  highlighter: 'marca-texto',
  'pencil-ruler': 'design projeto desenho',
  library: 'biblioteca livros',
  backpack: 'mochila escola',
  ruler: 'régua medida',
  calculator: 'calculadora',
  atom: 'ciência física química',
  languages: 'idioma tradução curso',
  award: 'certificado prêmio conquista',
  school: 'escola colégio',
  briefcase: 'trabalho maleta',
  'briefcase-business': 'negócio empresa trabalho',
  laptop: 'notebook computador',
  monitor: 'monitor tela',
  printer: 'impressora',
  building: 'prédio escritório empresa',
  'building-2': 'prédio empresa',
  factory: 'fábrica indústria',
  presentation: 'apresentação reunião',
  'hard-hat': 'obra construção capacete',
  handshake: 'acordo negócio parceria',
  clock: 'hora relógio',
  timer: 'cronômetro tempo',
  target: 'meta objetivo alvo',
  goal: 'meta objetivo',
  'notebook-pen': 'anotação nota',
  'clipboard-list': 'lista tarefa checklist',
  mailbox: 'caixa de correio',
  'chart-column': 'gráfico relatório',
  'chart-line': 'gráfico investimento',
  'chart-pie': 'gráfico',
  film: 'cinema filme',
  clapperboard: 'cinema filme',
  music: 'música',
  headphones: 'fone música podcast',
  guitar: 'violão instrumento música',
  piano: 'piano música',
  drum: 'bateria tambor música',
  radio: 'rádio',
  disc: 'disco cd',
  'disc-3': 'disco vinil',
  mic: 'microfone karaokê',
  'mic-vocal': 'microfone canto',
  'gamepad-2': 'jogo videogame',
  joystick: 'controle jogo',
  tv: 'televisão streaming',
  ticket: 'ingresso evento',
  palette: 'arte pintura hobby',
  camera: 'foto câmera',
  popcorn: 'pipoca cinema',
  drama: 'teatro',
  'party-popper': 'festa comemoração',
  dices: 'jogo dados',
  puzzle: 'quebra-cabeça jogo',
  spade: 'espadas baralho carta',
  club: 'paus baralho carta',
  volleyball: 'vôlei esporte',
  trophy: 'troféu prêmio',
  medal: 'medalha conquista',
  'map-pin': 'localização lugar',
  map: 'mapa',
  compass: 'bússola direção',
  globe: 'mundo internacional',
  luggage: 'mala bagagem viagem',
  hotel: 'hotel hospedagem',
  tent: 'camping acampamento',
  mountain: 'montanha trilha',
  'mountain-snow': 'montanha neve ski',
  'tree-palm': 'praia férias',
  trees: 'árvores floresta',
  'tree-deciduous': 'árvore natureza',
  'tree-pine': 'pinheiro floresta',
  flower: 'flor jardim',
  'flower-2': 'flor jardim',
  umbrella: 'guarda-chuva seguro',
  sun: 'sol clima',
  cloud: 'nuvem clima',
  'cloud-sun': 'tempo clima',
  'cloud-rain': 'chuva clima',
  wind: 'vento clima',
  snowflake: 'neve frio',
  waves: 'ondas mar praia',
  shell: 'concha praia',
  leaf: 'natureza planta',
  sprout: 'planta jardim horta',
  dog: 'cachorro pet',
  cat: 'gato pet',
  bird: 'pássaro pet',
  rabbit: 'coelho pet',
  turtle: 'tartaruga pet',
  rat: 'rato pet',
  squirrel: 'esquilo',
  snail: 'caracol lesma',
  worm: 'minhoca',
  bug: 'inseto bicho',
  feather: 'pena pássaro',
  bone: 'osso pet ração',
  'paw-print': 'pata pet animal',
  baby: 'bebê criança',
  user: 'pessoa perfil',
  'user-round': 'pessoa perfil',
  users: 'pessoas família grupo',
  contact: 'contato agenda',
  'person-standing': 'pessoa',
  'user-plus': 'adicionar pessoa',
  heart: 'coração amor',
  'hand-heart': 'doação caridade',
  'heart-handshake': 'doação apoio',
  banknote: 'dinheiro nota',
  wallet: 'carteira',
  'wallet-cards': 'carteira cartões',
  'piggy-bank': 'poupança cofrinho economia',
  'credit-card': 'cartão crédito',
  landmark: 'banco instituição',
  coins: 'moedas dinheiro',
  'dollar-sign': 'dinheiro dólar',
  'circle-dollar-sign': 'dinheiro moeda',
  'badge-dollar-sign': 'dinheiro salário',
  euro: 'euro moeda',
  'pound-sterling': 'libra moeda',
  'japanese-yen': 'iene moeda',
  'indian-rupee': 'rupia moeda',
  bitcoin: 'bitcoin cripto',
  'hand-coins': 'renda pagamento',
  scale: 'balança equilíbrio',
  'trending-up': 'alta lucro receita',
  'trending-down': 'baixa perda despesa',
  star: 'estrela favorito',
  sparkles: 'brilho especial',
  bookmark: 'marcador salvar',
  flag: 'bandeira meta',
  hash: 'hashtag número',
  shapes: 'formas',
  'grid-3x3': 'grade',
  box: 'caixa',
  circle: 'círculo',
  'more-horizontal': 'outros mais',
};

/** Humanized fallback label from a key (kebab -> spaces). */
function humanize(key: IconKey): string {
  return key.replace(/-/g, ' ');
}

export interface IconOption {
  key: IconKey;
  /** Human label used by the picker search (Portuguese when available). */
  label: string;
}

export const ICONS: readonly IconOption[] = ICON_KEYS.map((key) => ({
  key,
  label: ICON_LABELS[key] ?? humanize(key),
}));

/** Icon categories, WhatsApp-style, rendered as sections in the picker (order matters). */
export interface IconGroup {
  label: string;
  keys: readonly IconKey[];
}

export const ICON_GROUPS: readonly IconGroup[] = [
  {
    label: 'Alimentação',
    keys: [
      'utensils',
      'utensils-crossed',
      'pizza',
      'sandwich',
      'salad',
      'soup',
      'fish',
      'drumstick',
      'egg',
      'beef',
      'ham',
      'coffee',
      'wine',
      'beer',
      'martini',
      'cup-soda',
      'cake',
      'cookie',
      'croissant',
      'donut',
      'candy',
      'ice-cream-cone',
      'apple',
      'banana',
      'cherry',
      'grape',
      'citrus',
      'carrot',
      'milk',
      'nut',
      'wheat',
      'vegan',
    ],
  },
  {
    label: 'Compras',
    keys: [
      'shopping-cart',
      'shopping-bag',
      'shopping-basket',
      'store',
      'tag',
      'barcode',
      'percent',
      'badge-percent',
      'gift',
      'shirt',
      'glasses',
      'watch',
      'gem',
      'diamond',
      'crown',
      'footprints',
      'package',
      'boxes',
      'scissors',
      'spray-can',
    ],
  },
  {
    label: 'Transporte',
    keys: [
      'car',
      'bus-front',
      'train-front',
      'tram-front',
      'plane',
      'plane-takeoff',
      'rocket',
      'bike',
      'truck',
      'tractor',
      'forklift',
      'caravan',
      'ship',
      'sailboat',
      'anchor',
      'fuel',
      'car-taxi-front',
      'circle-parking',
      'navigation',
      'milestone',
    ],
  },
  {
    label: 'Casa',
    keys: [
      'house',
      'warehouse',
      'bed',
      'sofa',
      'armchair',
      'lamp',
      'bath',
      'shower-head',
      'cooking-pot',
      'washing-machine',
      'refrigerator',
      'door-open',
      'key',
      'plug',
      'wrench',
      'lightbulb',
      'hammer',
      'paintbrush',
      'paint-roller',
      'brush',
      'blinds',
      'fence',
      'trash-2',
      'recycle',
    ],
  },
  {
    label: 'Contas & Serviços',
    keys: [
      'wifi',
      'router',
      'signal',
      'antenna',
      'satellite-dish',
      'smartphone',
      'phone',
      'droplet',
      'flame',
      'zap',
      'mail',
      'at-sign',
      'send',
      'inbox',
      'file-text',
      'receipt',
      'newspaper',
      'calendar',
      'bell',
    ],
  },
  {
    label: 'Saúde',
    keys: [
      'heart-pulse',
      'stethoscope',
      'ambulance',
      'hospital',
      'pill',
      'tablets',
      'syringe',
      'cross',
      'activity',
      'brain',
      'bandage',
      'thermometer',
      'microscope',
      'test-tube',
      'dumbbell',
      'weight',
      'accessibility',
      'ear',
      'eye',
      'smile',
    ],
  },
  {
    label: 'Educação',
    keys: [
      'graduation-cap',
      'book',
      'book-open',
      'book-marked',
      'notebook',
      'pencil',
      'pen',
      'highlighter',
      'pencil-ruler',
      'library',
      'backpack',
      'ruler',
      'calculator',
      'atom',
      'languages',
      'award',
      'school',
    ],
  },
  {
    label: 'Trabalho',
    keys: [
      'briefcase',
      'briefcase-business',
      'laptop',
      'monitor',
      'printer',
      'building',
      'building-2',
      'factory',
      'presentation',
      'hard-hat',
      'handshake',
      'clock',
      'timer',
      'target',
      'goal',
      'notebook-pen',
      'clipboard-list',
      'mailbox',
      'chart-column',
      'chart-line',
      'chart-pie',
    ],
  },
  {
    label: 'Lazer & Entretenimento',
    keys: [
      'film',
      'clapperboard',
      'music',
      'headphones',
      'guitar',
      'piano',
      'drum',
      'radio',
      'disc',
      'disc-3',
      'mic',
      'mic-vocal',
      'gamepad-2',
      'joystick',
      'tv',
      'ticket',
      'palette',
      'camera',
      'popcorn',
      'drama',
      'party-popper',
      'dices',
      'puzzle',
      'spade',
      'club',
      'volleyball',
      'trophy',
      'medal',
    ],
  },
  {
    label: 'Viagem & Natureza',
    keys: [
      'map-pin',
      'map',
      'compass',
      'globe',
      'luggage',
      'hotel',
      'tent',
      'mountain',
      'mountain-snow',
      'tree-palm',
      'trees',
      'tree-deciduous',
      'tree-pine',
      'flower',
      'flower-2',
      'umbrella',
      'sun',
      'cloud',
      'cloud-sun',
      'cloud-rain',
      'wind',
      'snowflake',
      'waves',
      'shell',
      'leaf',
      'sprout',
    ],
  },
  {
    label: 'Pets',
    keys: [
      'dog',
      'cat',
      'bird',
      'rabbit',
      'turtle',
      'rat',
      'squirrel',
      'snail',
      'worm',
      'bug',
      'feather',
      'bone',
      'paw-print',
    ],
  },
  {
    label: 'Família & Pessoas',
    keys: [
      'baby',
      'user',
      'user-round',
      'users',
      'contact',
      'person-standing',
      'user-plus',
      'heart',
      'hand-heart',
      'heart-handshake',
    ],
  },
  {
    label: 'Finanças',
    keys: [
      'banknote',
      'wallet',
      'wallet-cards',
      'piggy-bank',
      'credit-card',
      'landmark',
      'coins',
      'dollar-sign',
      'circle-dollar-sign',
      'badge-dollar-sign',
      'euro',
      'pound-sterling',
      'japanese-yen',
      'indian-rupee',
      'bitcoin',
      'hand-coins',
      'scale',
      'trending-up',
      'trending-down',
    ],
  },
  {
    label: 'Outros',
    keys: [
      'star',
      'sparkles',
      'bookmark',
      'flag',
      'hash',
      'shapes',
      'grid-3x3',
      'box',
      'circle',
      'more-horizontal',
    ],
  },
];

export function isIconKey(value: string): value is IconKey {
  return iconKeySchema.safeParse(value).success;
}
